import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ToastContainer } from "react-toastify";

// Notification Sysstem
// @tanstack/store و sonner

// import { SessionProvider } from "next-auth/react";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        // ${geistSans.variable} ${geistMono.variable}
        //  m-auto
        //  px-4
        // اذا درتهم راح يسبب مشكل في dah Sidbar
        className={`antialiased min-h-screen container bg-gray-50
        `}>
        <ToastContainer />

        {children}
      </body>
    </html>
  );
}
